language: objective-c
osx_image: xcode9.3

xcode_project: Automatic Octo Parakeet.xcodeproj # path to your xcodeproj folder
xcode_scheme: Automatic Octo ParakeetTests
xcode_sdk: iphonesimulator11.3

cache:
- bundler
- cocoapods

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=fr_FR.UTF-8 LANG=fr_FR.UTF-8

scripts:
  - xcodebuild clean test -quiet -project Automatic\ Octo\ Parakeet.xcodeproj -scheme Automatic\ Octo\ ParakeetTests -destination 'platform=iOS Simulator,name=iPhone 7'

after_success:
  - bash <(curl -s https://codecov.io/bash)