language: swift
os: osx

xcode_project: Automatic Octo Parakeet.xcodeproj # path to your xcodeproj folder
xcode_scheme: Automatic Octo ParakeetTests

cache:
- bundler
- cocoapods

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=fr_FR.UTF-8 LANG=fr_FR.UTF-8

script:
  - xcodebuild clean test -quiet -project Automatic\ Octo\ Parakeet.xcodeproj -scheme Automatic\ Octo\ ParakeetTests -destination 'platform=iOS Simulator,name=iPhone 8 Plus'
  
after_success:
  - bash <(curl -s https://codecov.io/bash)